from __future__ import annotations

import importlib.util
import io
import json
import subprocess
import sys
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from contextlib import redirect_stderr, redirect_stdout
from datetime import datetime, timezone
from pathlib import Path
from unittest import mock


SCRIPT = Path(__file__).parents[1] / "scripts" / "echoes_vault.py"
SPEC = importlib.util.spec_from_file_location("echoes_vault", SCRIPT)
assert SPEC and SPEC.loader
echoes_vault = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(echoes_vault)


class EchoesVaultTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.workspace = Path(self.temp.name)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def run_cli(self, *args: str, stdin: dict | None = None) -> tuple[int, str, str]:
        old_stdin = sys.stdin
        stdout = io.StringIO()
        stderr = io.StringIO()
        if stdin is not None:
            sys.stdin = io.StringIO(json.dumps(stdin))
        try:
            with redirect_stdout(stdout), redirect_stderr(stderr):
                code = echoes_vault.main(["--workspace", str(self.workspace), *args])
        finally:
            sys.stdin = old_stdin
        return code, stdout.getvalue(), stderr.getvalue()

    def test_init_is_idempotent(self) -> None:
        code, output, _ = self.run_cli("init")
        self.assertEqual(code, 0)
        init_result = json.loads(output)
        self.assertTrue(init_result["created"])
        self.assertEqual(
            init_result["agentAdapters"]["managedAdapterVersion"], "1.1.1"
        )
        self.assertEqual(
            init_result["agentAdapters"]["codexAdapterVersion"], "1.1.1"
        )
        index = self.workspace / "EchoesVault" / "index.md"
        original = index.read_text(encoding="utf-8")
        self.assertIn("Generated by EchoesVault", original)
        self.assertTrue((self.workspace / "EchoesVault" / ".echoes-vault.json").is_file())
        self.assertIn("/index.md", (self.workspace / "EchoesVault" / ".gitignore").read_text())
        self.assertIn(
            "/state.json",
            (self.workspace / ".echoes-vault" / ".gitignore").read_text(),
        )
        marker = json.loads(
            (self.workspace / "EchoesVault" / ".echoes-vault.json").read_text()
        )
        self.assertEqual(marker["protocolVersion"], "1.0.0")
        self.assertTrue((self.workspace / ".echoes-vault" / "echoes_vault.py").is_file())
        self.assertTrue((self.workspace / "EchoesVault" / "AGENT_PROTOCOL.md").is_file())
        self.assertIn("echoes-vault:start", (self.workspace / "AGENTS.md").read_text())
        self.assertIn("echoes-vault:start", (self.workspace / "CLAUDE.md").read_text())
        self.assertTrue(
            (self.workspace / ".claude" / "skills" / "echoes-vault" / "SKILL.md").is_file()
        )
        self.assertTrue(
            (self.workspace / ".opencode" / "skills" / "echoes-vault" / "SKILL.md").is_file()
        )
        self.assertIn(
            "agent-neutral EchoesVault runtime",
            (self.workspace / ".opencode" / "commands" / "echoes-end.md").read_text(),
        )
        index.write_text(index.read_text() + "\nUser text\n", encoding="utf-8")
        code, output, _ = self.run_cli("init")
        self.assertEqual(code, 0)
        self.assertFalse(json.loads(output)["created"])
        self.assertEqual(index.read_text(encoding="utf-8"), original)

    def test_agent_guides_preserve_user_content_and_are_idempotent(self) -> None:
        (self.workspace / "AGENTS.md").write_text("# Team rules\n\nKeep this.\n")
        (self.workspace / "CLAUDE.md").write_text("# Claude rules\n\nKeep this too.\n")
        self.run_cli("init")
        first_agents = (self.workspace / "AGENTS.md").read_text()
        first_claude = (self.workspace / "CLAUDE.md").read_text()
        self.run_cli("configure-agents")
        self.assertEqual((self.workspace / "AGENTS.md").read_text(), first_agents)
        self.assertEqual((self.workspace / "CLAUDE.md").read_text(), first_claude)
        self.assertIn("Keep this.", first_agents)
        self.assertIn("Keep this too.", first_claude)
        self.assertEqual(first_agents.count(echoes_vault.AGENT_GUIDE_START), 1)
        self.assertEqual(first_claude.count(echoes_vault.AGENT_GUIDE_START), 1)

    def test_portable_runtime_operates_without_plugin_specific_paths(self) -> None:
        self.run_cli("init")
        runtime = self.workspace / ".echoes-vault" / "echoes_vault.py"
        result = subprocess.run(
            [
                sys.executable,
                str(runtime),
                "--workspace",
                str(self.workspace),
                "protocol",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        protocol = json.loads(result.stdout)
        self.assertEqual(protocol["supportedProtocolVersion"], "1.0.0")
        self.assertEqual(protocol["vaultProtocolVersion"], "1.0.0")

    def test_older_launcher_delegates_to_newer_project_runtime_without_downgrade(self) -> None:
        self.run_cli("init")
        runtime = self.workspace / ".echoes-vault" / "echoes_vault.py"
        current = runtime.read_text(encoding="utf-8")
        newer = current.replace('ENGINE_VERSION = "1.1.1"', 'ENGINE_VERSION = "9.0.0"')
        newer += "\n# newer-project-runtime-sentinel\n"
        runtime.write_text(newer, encoding="utf-8")

        old_launcher = self.workspace / "old-codex-launcher.py"
        old_launcher.write_text(
            SCRIPT.read_text(encoding="utf-8")
            .replace(
                'MANAGED_ADAPTER_VERSION = "1.1.1"',
                'MANAGED_ADAPTER_VERSION = "1.0.0"',
            )
            .replace('ENGINE_VERSION = "1.1.1"', 'ENGINE_VERSION = "1.0.0"'),
            encoding="utf-8",
        )
        result = subprocess.run(
            [
                sys.executable,
                str(old_launcher),
                "--workspace",
                str(self.workspace),
                "upgrade",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        self.assertEqual(json.loads(result.stdout)["state"]["engineVersion"], "9.0.0")
        installed = runtime.read_text(encoding="utf-8")
        self.assertIn('ENGINE_VERSION = "9.0.0"', installed)
        self.assertIn("newer-project-runtime-sentinel", installed)

    def test_explicit_upgrade_repairs_an_older_project_runtime(self) -> None:
        self.run_cli("init")
        runtime = self.workspace / ".echoes-vault" / "echoes_vault.py"
        runtime.write_text(
            runtime.read_text(encoding="utf-8").replace(
                'ENGINE_VERSION = "1.1.1"', 'ENGINE_VERSION = "1.0.0"'
            ),
            encoding="utf-8",
        )
        code, _, error = self.run_cli("start")
        self.assertEqual(code, 2)
        self.assertIn("older than engine 1.1.1", error)
        code, _, error = self.run_cli("upgrade")
        self.assertEqual(code, 0, error)
        self.assertIn('ENGINE_VERSION = "1.1.1"', runtime.read_text())

    def test_init_replaces_recognized_legacy_opencode_commands(self) -> None:
        command = self.workspace / ".opencode" / "commands" / "echoes-end.md"
        command.parent.mkdir(parents=True)
        command.write_text(
            "# Legacy\n\nCall commit_memory_to_echoes_vault with indexUpdates.\n",
            encoding="utf-8",
        )
        code, _, error = self.run_cli("init")
        self.assertEqual(code, 0, error)
        migrated = command.read_text(encoding="utf-8")
        self.assertIn("Generated by EchoesVault protocol 1.0.0", migrated)
        self.assertNotIn("indexUpdates", migrated)

    def test_init_preserves_unrelated_opencode_command_and_reports_it(self) -> None:
        command = self.workspace / ".opencode" / "commands" / "echoes-status.md"
        command.parent.mkdir(parents=True)
        custom = "# User-owned command\n\nDo something unrelated.\n"
        command.write_text(custom, encoding="utf-8")
        code, _, error = self.run_cli("init")
        self.assertEqual(code, 0, error)
        self.assertEqual(command.read_text(), custom)
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertIn(
            ".opencode/commands/echoes-status.md", health["missingStructure"]
        )
        self.assertEqual(health["integrity"], "attention")

    def test_explicit_upgrade_repairs_same_version_portable_runtime(self) -> None:
        self.run_cli("init")
        runtime = self.workspace / ".echoes-vault" / "echoes_vault.py"
        runtime.write_text(runtime.read_text() + "\n# accidental edit\n", encoding="utf-8")
        code, output, error = self.run_cli("upgrade")
        self.assertEqual(code, 0, error)
        self.assertFalse(json.loads(output)["agentAdapters"]["runtimeUpdated"])
        self.assertNotIn("accidental edit", runtime.read_text())

    def test_unsupported_protocol_fails_closed(self) -> None:
        self.run_cli("init")
        marker = self.workspace / "EchoesVault" / ".echoes-vault.json"
        payload = json.loads(marker.read_text())
        payload["protocolVersion"] = "2.0.0"
        marker.write_text(json.dumps(payload), encoding="utf-8")
        code, _, error = self.run_cli(
            "append", "--payload", "-", stdin={"entry": "Must not be written."}
        )
        self.assertEqual(code, 2)
        self.assertIn("Unsupported EchoesVault protocol", error)
        self.assertEqual(list((self.workspace / "EchoesVault" / "daily").rglob("*.md")), [])

    def test_legacy_codex_state_migrates_to_agent_neutral_state(self) -> None:
        legacy = self.workspace / ".codex" / "echoes-vault-state.json"
        legacy.parent.mkdir(parents=True)
        legacy.write_text(
            json.dumps(
                {
                    "initialized": True,
                    "session": {
                        "started": True,
                        "saved": False,
                        "lastStart": "2026-01-01T00:00:00+00:00",
                        "lastSave": None,
                    },
                }
            ),
            encoding="utf-8",
        )
        self.run_cli("init")
        state = json.loads((self.workspace / ".echoes-vault" / "state.json").read_text())
        self.assertTrue(state["session"]["started"])
        self.assertEqual(state["version"], 4)
        self.assertEqual(state["engineVersion"], "1.1.1")
        self.assertEqual(state["lastWriter"]["agent"], "codex")
        self.assertNotIn("pluginVersion", state)
        self.assertNotIn("runtimeVersion", state)

    def test_legacy_opencode_state_has_priority_and_preserves_session(self) -> None:
        codex_state = self.workspace / ".codex" / "echoes-vault-state.json"
        codex_state.parent.mkdir(parents=True)
        codex_state.write_text(
            json.dumps({"initialized": False, "session": {"started": False}}),
            encoding="utf-8",
        )
        opencode_state = self.workspace / ".opencode" / "echoes-state.json"
        opencode_state.parent.mkdir(parents=True)
        opencode_state.write_text(
            json.dumps(
                {
                    "initialized": True,
                    "session": {
                        "started": True,
                        "saved": True,
                        "lastStart": "2026-08-31T10:00:00.000Z",
                        "lastSave": "2026-08-31T11:00:00.000Z",
                    },
                    "pluginVersion": "1.2.3",
                }
            ),
            encoding="utf-8",
        )
        code, _, error = self.run_cli("migrate")
        self.assertEqual(code, 0, error)
        state = json.loads((self.workspace / ".echoes-vault" / "state.json").read_text())
        self.assertTrue(state["initialized"])
        self.assertTrue(state["session"]["started"])
        self.assertTrue(state["session"]["saved"])
        self.assertEqual(state["session"]["lastStart"], "2026-08-31T10:00:00.000Z")
        self.assertEqual(state["session"]["lastSave"], "2026-08-31T11:00:00.000Z")
        self.assertEqual(state["lastWriter"], {"agent": "opencode", "adapterVersion": "1.2.3"})

    def test_init_redirects_known_legacy_opencode_skills_and_preserves_unknown(self) -> None:
        known = (
            self.workspace
            / ".opencode"
            / "skills"
            / "echoes-append-to-daily-log"
            / "SKILL.md"
        )
        known.parent.mkdir(parents=True)
        known.write_text("Call echoes_append_to_daily_log directly.\n", encoding="utf-8")
        unknown = (
            self.workspace
            / ".opencode"
            / "skills"
            / "echoes-search-vault-pages"
            / "SKILL.md"
        )
        unknown.parent.mkdir(parents=True)
        custom = "# User-owned skill\n\nKeep this implementation.\n"
        unknown.write_text(custom, encoding="utf-8")

        code, output, error = self.run_cli("init")
        self.assertEqual(code, 0, error)
        adapters = json.loads(output)["agentAdapters"]
        self.assertIn(
            ".opencode/skills/echoes-append-to-daily-log/SKILL.md",
            adapters["legacySkillsRedirected"],
        )
        self.assertIn("Legacy redirect", known.read_text())
        self.assertEqual(unknown.read_text(), custom)
        self.assertIn(
            ".opencode/skills/echoes-search-vault-pages/SKILL.md",
            adapters["adapterConflicts"],
        )

    def test_status_is_strictly_read_only(self) -> None:
        self.run_cli("init")
        index = self.workspace / "EchoesVault" / "index.md"
        index.write_text(index.read_text() + "\nLocal stale text.\n", encoding="utf-8")

        def snapshot() -> dict[str, bytes]:
            return {
                str(path.relative_to(self.workspace)): path.read_bytes()
                for path in self.workspace.rglob("*")
                if path.is_file() and not path.is_symlink()
            }

        before = snapshot()
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        self.assertEqual(snapshot(), before)
        self.assertEqual(json.loads(output)["health"]["indexOutOfDate"], ["index.md"])

    def test_legacy_status_card_requires_explicit_migration(self) -> None:
        vault = self.workspace / "EchoesVault"
        vault.mkdir()
        (vault / "index.md").write_text(echoes_vault.DEFAULT_INDEX, encoding="utf-8")
        before = (vault / "index.md").read_bytes()
        code, card, error = self.run_cli("inspect", "--format", "card")
        self.assertEqual(code, 0, error)
        self.assertIn("Legacy vault detected", card)
        self.assertEqual((vault / "index.md").read_bytes(), before)
        self.assertFalse((vault / ".echoes-vault.json").exists())

    def test_upsert_search_and_status(self) -> None:
        self.run_cli("init")
        page = {
            "filename": "auth-architecture.md",
            "content": (
                "---\ntype: architecture\nstack: [python]\nstatus: active\n---\n\n"
                "# Auth architecture\n\nJWT validation lives at the boundary.\n"
            ),
            "indexDescription": "Authentication boundaries and token flow.",
        }
        code, output, _ = self.run_cli("upsert", "--payload", "-", stdin=page)
        self.assertEqual(code, 0)
        result = json.loads(output)
        self.assertEqual(result["action"], "created")
        code, output, _ = self.run_cli("search", "jwt")
        self.assertEqual(code, 0)
        self.assertEqual(len(json.loads(output)["results"]), 1)
        code, output, _ = self.run_cli("status")
        status = json.loads(output)
        self.assertEqual(status["health"]["totalPages"], 1)
        self.assertEqual(status["health"]["indexTopics"], 1)
        self.assertEqual(status["health"]["orphanPages"], [])

    def test_status_reports_storage_integrity_and_card(self) -> None:
        self.run_cli("init")
        invalid_page = self.workspace / "EchoesVault" / "pages" / "broken.md"
        invalid_page.write_text("# Missing frontmatter\n", encoding="utf-8")
        asset = self.workspace / "EchoesVault" / "assets" / "sample.bin"
        asset.write_bytes(b"echoes")

        code, output, _ = self.run_cli("status")
        self.assertEqual(code, 0)
        status = json.loads(output)
        health = status["health"]
        self.assertGreaterEqual(health["storage"]["totalBytes"], len(b"echoes"))
        self.assertGreaterEqual(health["storage"]["totalFiles"], 3)
        self.assertEqual(health["invalidFrontmatter"], ["broken"])
        self.assertEqual(health["orphanPages"], ["broken"])
        self.assertEqual(health["integrity"], "attention")

        code, card, _ = self.run_cli("status", "--format", "card")
        self.assertEqual(code, 0)
        self.assertIn("EchoesVault", card)
        self.assertIn("Needs attention", card)
        self.assertIn("Protocol: 1.0.0", card)
        self.assertIn("invalid frontmatter: 1", card)
        self.assertIn("orphan pages: 1", card)

    def test_uninitialized_status_card_is_actionable(self) -> None:
        code, card, _ = self.run_cli("status", "--format", "card")
        self.assertEqual(code, 0)
        self.assertIn("Not initialized", card)
        self.assertIn("Initialize or restore", card)

    def test_existing_page_requires_current_hash(self) -> None:
        self.run_cli("init")
        original = {
            "filename": "decision.md",
            "content": "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# One\n",
            "indexDescription": "A decision.",
        }
        self.run_cli("upsert", "--payload", "-", stdin=original)
        changed = dict(original)
        changed["content"] = "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# Two\n"
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=changed)
        self.assertEqual(code, 2)
        self.assertIn("expectedSha256", error)
        current = (self.workspace / "EchoesVault" / "pages" / "decision.md").read_text()
        changed["expectedSha256"] = echoes_vault.sha256_text(current)
        code, output, _ = self.run_cli("upsert", "--payload", "-", stdin=changed)
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(output)["action"], "updated")

    def test_rejects_unsafe_filename_and_invalid_frontmatter(self) -> None:
        self.run_cli("init")
        unsafe = {
            "filename": "../outside.md",
            "content": "---\ntype: note\nstack: []\nstatus: active\n---\n",
            "indexDescription": "Unsafe.",
        }
        code, _, _ = self.run_cli("upsert", "--payload", "-", stdin=unsafe)
        self.assertEqual(code, 2)
        invalid = {
            "filename": "invalid.md",
            "content": "# Missing metadata\n",
            "indexDescription": "Invalid.",
        }
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=invalid)
        self.assertEqual(code, 2)
        self.assertIn("frontmatter", error)

        empty_value = {
            "filename": "empty-value.md",
            "content": "---\ntype:\nstack: []\nstatus: active\n---\n",
            "indexDescription": "Invalid.",
        }
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=empty_value)
        self.assertEqual(code, 2)
        self.assertIn("type", error)

    def test_rejects_vault_symlink_escape(self) -> None:
        with tempfile.TemporaryDirectory() as outside_name:
            outside = Path(outside_name)
            (self.workspace / "EchoesVault").symlink_to(outside, target_is_directory=True)
            code, _, error = self.run_cli("init")
            self.assertEqual(code, 2)
            self.assertIn("escapes the workspace", error)

    def test_end_requires_explicit_confirmation(self) -> None:
        self.run_cli("init")
        payload = {"dailySummary": "- Completed tests.", "pages": [], "indexUpdates": []}
        code, _, error = self.run_cli("end", "--payload", "-", stdin=payload)
        self.assertEqual(code, 2)
        self.assertIn("confirm-explicit-user-end", error)
        code, output, _ = self.run_cli(
            "end", "--confirm-explicit-user-end", "--payload", "-", stdin=payload
        )
        self.assertEqual(code, 0)
        self.assertTrue(json.loads(output)["memorySaved"])
        daily_files = list((self.workspace / "EchoesVault" / "daily").rglob("*.md"))
        self.assertEqual(len(daily_files), 1)
        self.assertIn("Completed tests", daily_files[0].read_text(encoding="utf-8"))

    def test_generated_index_is_sorted_and_ignores_page_body_changes(self) -> None:
        self.run_cli("init")
        for filename, summary in (
            ("zeta.md", "Zeta knowledge."),
            ("alpha.md", "Alpha knowledge."),
        ):
            payload = {
                "filename": filename,
                "content": (
                    "---\ntype: note\nstack: []\nstatus: active\n"
                    f"summary: {summary}\n---\n\n# Page\n\nBody one.\n"
                ),
            }
            code, _, error = self.run_cli("upsert", "--payload", "-", stdin=payload)
            self.assertEqual(code, 0, error)

        index = self.workspace / "EchoesVault" / "index.md"
        before = index.read_text(encoding="utf-8")
        self.assertLess(before.index("[[alpha]]"), before.index("[[zeta]]"))

        page = self.workspace / "EchoesVault" / "pages" / "zeta.md"
        updated = {
            "filename": "zeta.md",
            "content": page.read_text(encoding="utf-8").replace("Body one.", "Body two."),
            "expectedSha256": echoes_vault.sha256_text(page.read_text(encoding="utf-8")),
        }
        code, output, error = self.run_cli("upsert", "--payload", "-", stdin=updated)
        self.assertEqual(code, 0, error)
        self.assertFalse(json.loads(output)["indexChanged"])
        self.assertEqual(index.read_text(encoding="utf-8"), before)

    def test_legacy_index_description_migrates_to_summary(self) -> None:
        self.run_cli("init")
        page = self.workspace / "EchoesVault" / "pages" / "legacy.md"
        page.write_text(
            "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# Legacy\n",
            encoding="utf-8",
        )
        index = self.workspace / "EchoesVault" / "index.md"
        index.write_text(
            echoes_vault.DEFAULT_INDEX + "\n- [[legacy]]: Migrated legacy description.\n",
            encoding="utf-8",
        )

        before_page = page.read_text()
        before_index = index.read_text()
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(status["indexRefresh"]["migratedSummaries"], [])
        self.assertEqual(page.read_text(), before_page)
        self.assertEqual(index.read_text(), before_index)
        code, output, error = self.run_cli("migrate")
        self.assertEqual(code, 0, error)
        self.assertEqual(json.loads(output)["indexRefresh"]["migratedSummaries"], ["legacy.md"])
        self.assertIn("summary: \"Migrated legacy description.\"", page.read_text())
        self.assertIn("[[legacy]]: Migrated legacy description.", index.read_text())

    def test_status_preserves_index_when_page_metadata_is_invalid(self) -> None:
        self.run_cli("init")
        index = self.workspace / "EchoesVault" / "index.md"
        before = index.read_text(encoding="utf-8")
        broken = self.workspace / "EchoesVault" / "pages" / "broken.md"
        broken.write_text(
            "---\ntype: note\nstack: []\nstatus: active\n---\n\n# Broken\n",
            encoding="utf-8",
        )

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(index.read_text(encoding="utf-8"), before)
        self.assertEqual(status["health"]["integrity"], "attention")
        self.assertEqual(status["health"]["invalidFrontmatter"], ["broken"])
        self.assertTrue(status["health"]["indexBuildErrors"])

    def test_index_rejects_unicode_equivalent_page_names(self) -> None:
        with self.assertRaisesRegex(echoes_vault.EchoesError, "collide across filesystems"):
            echoes_vault.validate_unique_page_names(
                [Path("café.md"), Path("cafe\u0301.md")]
            )

    def test_status_detects_git_conflict_markers(self) -> None:
        self.run_cli("init")
        page = self.workspace / "EchoesVault" / "pages" / "conflicted.md"
        page.write_text(
            "---\ntype: note\nstack: []\nstatus: active\n"
            "summary: Conflicted page.\n---\n\n<<<<<<< HEAD\nA\n=======\nB\n>>>>>>> branch\n",
            encoding="utf-8",
        )
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(status["health"]["conflictMarkers"], ["pages/conflicted.md"])
        self.assertEqual(status["health"]["integrity"], "attention")

    def test_each_log_write_uses_a_unique_file(self) -> None:
        self.run_cli("init")
        for entry in ("One", "Two"):
            code, _, error = self.run_cli("append", "--payload", "-", stdin={"entry": entry})
            self.assertEqual(code, 0, error)
        daily_files = list((self.workspace / "EchoesVault" / "daily").rglob("*.md"))
        self.assertEqual(len(daily_files), 2)
        self.assertEqual(len({item.name for item in daily_files}), 2)
        self.assertTrue(all(item.parent.name == echoes_vault.utc_today() for item in daily_files))
        self.assertTrue(all("Z-" in item.name for item in daily_files))

    def test_logs_can_record_cross_agent_provenance(self) -> None:
        self.run_cli("init")
        for agent in ("codex", "opencode", "claude"):
            code, output, error = self.run_cli(
                "append",
                "--payload",
                "-",
                stdin={"entry": f"Written by {agent}.", "agent": agent},
            )
            self.assertEqual(code, 0, error)
            result = json.loads(output)
            self.assertEqual(result["agent"], agent)
            daily = Path(result["dailyLog"])
            self.assertIn(f"-scratchpad-{agent}-", daily.name)
            self.assertIn(f"Agent: `{agent}`", daily.read_text())

    def test_daily_paths_sort_by_utc_across_local_time_zones(self) -> None:
        paths = echoes_vault.vault_paths(self.workspace.resolve())
        paths["daily"].mkdir(parents=True)
        utc_moments = [
            datetime(2026, 9, 4, 23, 59, 59, 999999, tzinfo=timezone.utc),
            datetime(2026, 9, 5, 0, 0, 0, 1, tzinfo=timezone.utc),
        ]
        with mock.patch.object(echoes_vault, "utc_now", side_effect=utc_moments):
            first = echoes_vault.new_daily_log(paths, "scratchpad", "west\n", "codex")
            second = echoes_vault.new_daily_log(paths, "scratchpad", "east\n", "opencode")
        self.assertEqual(first.parent.name, "2026-09-04")
        self.assertEqual(second.parent.name, "2026-09-05")
        self.assertIn("T235959999999Z-", first.name)
        self.assertIn("T000000000001Z-", second.name)
        self.assertEqual(echoes_vault.daily_markdown_files(paths["daily"]), [first, second])

    def test_codex_and_opencode_share_runtime_state_and_knowledge(self) -> None:
        code, _, error = self.run_cli(
            "--agent", "codex", "--adapter-version", "1.1.1", "init"
        )
        self.assertEqual(code, 0, error)
        code, output, error = self.run_cli(
            "--agent",
            "opencode",
            "--adapter-version",
            "1.2.3",
            "append",
            "--payload",
            "-",
            stdin={"entry": "Written through the shared engine."},
        )
        self.assertEqual(code, 0, error)
        self.assertIn("-scratchpad-opencode-", Path(json.loads(output)["dailyLog"]).name)
        code, context, error = self.run_cli(
            "--agent", "codex", "--adapter-version", "1.1.1", "start"
        )
        self.assertEqual(code, 0, error)
        self.assertIn("Written through the shared engine.", context)
        state = json.loads((self.workspace / ".echoes-vault" / "state.json").read_text())
        self.assertEqual(state["lastWriter"]["agent"], "codex")

    def test_opencode_init_codex_upsert_opencode_status(self) -> None:
        code, _, error = self.run_cli(
            "--agent", "opencode", "--adapter-version", "1.2.3", "init"
        )
        self.assertEqual(code, 0, error)
        payload = {
            "filename": "shared-contract.md",
            "content": (
                "---\ntype: contract\nstack: [python]\nstatus: active\n"
                "summary: Shared cross-agent contract.\n---\n\n# Shared contract\n"
            ),
        }
        code, _, error = self.run_cli(
            "--agent",
            "codex",
            "--adapter-version",
            "1.1.1",
            "upsert",
            "--payload",
            "-",
            stdin=payload,
        )
        self.assertEqual(code, 0, error)
        code, output, error = self.run_cli(
            "--agent", "opencode", "--adapter-version", "1.2.3", "status"
        )
        self.assertEqual(code, 0, error)
        self.assertEqual(json.loads(output)["health"]["totalPages"], 1)

    def test_git_readiness_reports_root_ignored_opencode_adapters(self) -> None:
        subprocess.run(
            ["git", "-C", str(self.workspace), "init", "-b", "main"],
            check=True,
            capture_output=True,
            text=True,
        )
        (self.workspace / ".gitignore").write_text(".opencode/\n", encoding="utf-8")
        self.run_cli("init")
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        git_health = json.loads(output)["health"]["git"]
        self.assertFalse(git_health["ready"])
        self.assertTrue(git_health["openCodeCommandsIgnored"])
        self.assertTrue(git_health["openCodeSkillsIgnored"])
        self.assertTrue(any(command.startswith("git add -f --") for command in git_health["suggestedCommands"]))

    def test_git_readiness_reports_accidentally_tracked_local_files(self) -> None:
        subprocess.run(
            ["git", "-C", str(self.workspace), "init", "-b", "main"],
            check=True,
            capture_output=True,
            text=True,
        )
        self.run_cli("init")
        subprocess.run(
            [
                "git",
                "-C",
                str(self.workspace),
                "add",
                "-f",
                "EchoesVault/index.md",
                ".echoes-vault/state.json",
            ],
            check=True,
        )
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        git_health = json.loads(output)["health"]["git"]
        self.assertEqual(
            git_health["trackedLocalFiles"],
            [".echoes-vault/state.json", "EchoesVault/index.md"],
        )
        self.assertTrue(
            any(command.startswith("git rm --cached --") for command in git_health["suggestedCommands"])
        )

    def test_parallel_writes_keep_every_page_indexed(self) -> None:
        self.run_cli("init")

        def create_page(number: int) -> subprocess.CompletedProcess[str]:
            payload = {
                "filename": f"parallel-{number}.md",
                "content": (
                    "---\ntype: note\nstack: [test]\nstatus: active\n"
                    f"summary: Parallel page {number}.\n---\n\n# Parallel {number}\n"
                ),
            }
            return subprocess.run(
                [
                    sys.executable,
                    str(self.workspace / ".echoes-vault" / "echoes_vault.py"),
                    "--workspace",
                    str(self.workspace),
                    "upsert",
                    "--payload",
                    "-",
                ],
                input=json.dumps(payload),
                capture_output=True,
                text=True,
            )

        with ThreadPoolExecutor(max_workers=8) as pool:
            results = list(pool.map(create_page, range(24)))
        self.assertTrue(all(result.returncode == 0 for result in results))

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["totalPages"], 24)
        self.assertEqual(health["indexTopics"], 24)
        self.assertEqual(health["orphanPages"], [])
        self.assertEqual(health["integrity"], "healthy")

    def test_parallel_processes_keep_daily_logs_and_pages(self) -> None:
        self.run_cli("init")
        runtime = self.workspace / ".echoes-vault" / "echoes_vault.py"

        def write(number: int) -> subprocess.CompletedProcess[str]:
            if number % 2:
                command = ["append", "--payload", "-"]
                payload = {"entry": f"Concurrent log {number}.", "agent": "opencode"}
            else:
                command = ["upsert", "--payload", "-"]
                payload = {
                    "filename": f"mixed-{number}.md",
                    "content": (
                        "---\ntype: note\nstack: [test]\nstatus: active\n"
                        f"summary: Mixed concurrent page {number}.\n---\n\n# Mixed {number}\n"
                    ),
                }
            return subprocess.run(
                [
                    sys.executable,
                    str(runtime),
                    "--workspace",
                    str(self.workspace),
                    "--agent",
                    "opencode" if number % 2 else "codex",
                    "--adapter-version",
                    "1.1.1",
                    *command,
                ],
                input=json.dumps(payload),
                capture_output=True,
                text=True,
            )

        with ThreadPoolExecutor(max_workers=8) as pool:
            results = list(pool.map(write, range(20)))
        self.assertTrue(all(result.returncode == 0 for result in results))
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["totalPages"], 10)
        self.assertEqual(health["totalDailyLogs"], 10)
        self.assertEqual(health["indexTopics"], 10)

    def test_independent_git_branches_merge_without_generated_file_conflicts(self) -> None:
        def git(*args: str) -> subprocess.CompletedProcess[str]:
            return subprocess.run(
                ["git", "-C", str(self.workspace), *args],
                check=True,
                capture_output=True,
                text=True,
            )

        git("init", "-b", "main")
        git("config", "user.name", "EchoesVault Test")
        git("config", "user.email", "echoes@example.invalid")
        self.run_cli("init")
        git("add", "-A")
        git("commit", "-m", "Initialize vault")
        tracked = git("ls-files").stdout.splitlines()
        self.assertNotIn("EchoesVault/index.md", tracked)
        self.assertNotIn(".echoes-vault/state.json", tracked)
        self.assertNotIn(".echoes-vault/lock", tracked)
        self.assertIn(".echoes-vault/echoes_vault.py", tracked)
        self.assertIn("EchoesVault/AGENT_PROTOCOL.md", tracked)
        self.assertIn("AGENTS.md", tracked)
        self.assertIn("CLAUDE.md", tracked)
        self.assertIn(".opencode/commands/echoes-end.md", tracked)

        git("switch", "-c", "developer-a")
        page_a = {
            "filename": "alpha.md",
            "content": (
                "---\ntype: note\nstack: [git]\nstatus: active\n"
                "summary: Knowledge from developer A.\n---\n\n# Alpha\n"
            ),
        }
        self.assertEqual(self.run_cli("upsert", "--payload", "-", stdin=page_a)[0], 0)
        self.assertEqual(self.run_cli("append", "--payload", "-", stdin={"entry": "A"})[0], 0)
        git("add", "-A")
        git("commit", "-m", "Add developer A knowledge")

        git("switch", "main")
        git("switch", "-c", "developer-b")
        page_b = {
            "filename": "beta.md",
            "content": (
                "---\ntype: note\nstack: [git]\nstatus: active\n"
                "summary: Knowledge from developer B.\n---\n\n# Beta\n"
            ),
        }
        self.assertEqual(self.run_cli("upsert", "--payload", "-", stdin=page_b)[0], 0)
        self.assertEqual(self.run_cli("append", "--payload", "-", stdin={"entry": "B"})[0], 0)
        git("add", "-A")
        git("commit", "-m", "Add developer B knowledge")
        merge = git("merge", "--no-edit", "developer-a")
        self.assertNotIn("CONFLICT", merge.stdout + merge.stderr)

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["integrity"], "attention")
        self.assertEqual(health["indexOutOfDate"], ["index.md"])
        code, _, error = self.run_cli("hydrate")
        self.assertEqual(code, 0, error)
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["totalPages"], 2)
        self.assertEqual(health["totalDailyLogs"], 2)
        self.assertEqual(health["integrity"], "healthy")
        generated_index = (self.workspace / "EchoesVault" / "index.md").read_text()
        self.assertIn("[[alpha]]", generated_index)
        self.assertIn("[[beta]]", generated_index)


if __name__ == "__main__":
    unittest.main()
