from __future__ import annotations

import importlib.util
import io
import json
import subprocess
import sys
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path


SCRIPT = Path(__file__).parents[1] / "scripts" / "echoes_vault.py"
SPEC = importlib.util.spec_from_file_location("echoes_vault", SCRIPT)
assert SPEC and SPEC.loader
echoes_vault = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(echoes_vault)


class EchoesVaultTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.workspace = Path(self.temp.name)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def run_cli(self, *args: str, stdin: dict | None = None) -> tuple[int, str, str]:
        old_stdin = sys.stdin
        stdout = io.StringIO()
        stderr = io.StringIO()
        if stdin is not None:
            sys.stdin = io.StringIO(json.dumps(stdin))
        try:
            with redirect_stdout(stdout), redirect_stderr(stderr):
                code = echoes_vault.main(["--workspace", str(self.workspace), *args])
        finally:
            sys.stdin = old_stdin
        return code, stdout.getvalue(), stderr.getvalue()

    def test_init_is_idempotent(self) -> None:
        code, output, _ = self.run_cli("init")
        self.assertEqual(code, 0)
        self.assertTrue(json.loads(output)["created"])
        index = self.workspace / "EchoesVault" / "index.md"
        original = index.read_text(encoding="utf-8")
        self.assertIn("Generated by EchoesVault", original)
        self.assertTrue((self.workspace / "EchoesVault" / ".echoes-vault.json").is_file())
        self.assertIn("/index.md", (self.workspace / "EchoesVault" / ".gitignore").read_text())
        self.assertIn(
            "/echoes-vault-state.json",
            (self.workspace / ".codex" / ".gitignore").read_text(),
        )
        index.write_text(index.read_text() + "\nUser text\n", encoding="utf-8")
        code, output, _ = self.run_cli("init")
        self.assertEqual(code, 0)
        self.assertFalse(json.loads(output)["created"])
        self.assertEqual(index.read_text(encoding="utf-8"), original)

    def test_upsert_search_and_status(self) -> None:
        self.run_cli("init")
        page = {
            "filename": "auth-architecture.md",
            "content": (
                "---\ntype: architecture\nstack: [python]\nstatus: active\n---\n\n"
                "# Auth architecture\n\nJWT validation lives at the boundary.\n"
            ),
            "indexDescription": "Authentication boundaries and token flow.",
        }
        code, output, _ = self.run_cli("upsert", "--payload", "-", stdin=page)
        self.assertEqual(code, 0)
        result = json.loads(output)
        self.assertEqual(result["action"], "created")
        code, output, _ = self.run_cli("search", "jwt")
        self.assertEqual(code, 0)
        self.assertEqual(len(json.loads(output)["results"]), 1)
        code, output, _ = self.run_cli("status")
        status = json.loads(output)
        self.assertEqual(status["health"]["totalPages"], 1)
        self.assertEqual(status["health"]["indexTopics"], 1)
        self.assertEqual(status["health"]["orphanPages"], [])

    def test_status_reports_storage_integrity_and_card(self) -> None:
        self.run_cli("init")
        invalid_page = self.workspace / "EchoesVault" / "pages" / "broken.md"
        invalid_page.write_text("# Missing frontmatter\n", encoding="utf-8")
        asset = self.workspace / "EchoesVault" / "assets" / "sample.bin"
        asset.write_bytes(b"echoes")

        code, output, _ = self.run_cli("status")
        self.assertEqual(code, 0)
        status = json.loads(output)
        health = status["health"]
        self.assertGreaterEqual(health["storage"]["totalBytes"], len(b"echoes"))
        self.assertGreaterEqual(health["storage"]["totalFiles"], 3)
        self.assertEqual(health["invalidFrontmatter"], ["broken"])
        self.assertEqual(health["orphanPages"], ["broken"])
        self.assertEqual(health["integrity"], "attention")

        code, card, _ = self.run_cli("status", "--format", "card")
        self.assertEqual(code, 0)
        self.assertIn("EchoesVault", card)
        self.assertIn("Needs attention", card)
        self.assertIn("invalid frontmatter: 1", card)
        self.assertIn("orphan pages: 1", card)

    def test_uninitialized_status_card_is_actionable(self) -> None:
        code, card, _ = self.run_cli("status", "--format", "card")
        self.assertEqual(code, 0)
        self.assertIn("Not initialized", card)
        self.assertIn("Initialize or restore", card)

    def test_existing_page_requires_current_hash(self) -> None:
        self.run_cli("init")
        original = {
            "filename": "decision.md",
            "content": "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# One\n",
            "indexDescription": "A decision.",
        }
        self.run_cli("upsert", "--payload", "-", stdin=original)
        changed = dict(original)
        changed["content"] = "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# Two\n"
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=changed)
        self.assertEqual(code, 2)
        self.assertIn("expectedSha256", error)
        current = (self.workspace / "EchoesVault" / "pages" / "decision.md").read_text()
        changed["expectedSha256"] = echoes_vault.sha256_text(current)
        code, output, _ = self.run_cli("upsert", "--payload", "-", stdin=changed)
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(output)["action"], "updated")

    def test_rejects_unsafe_filename_and_invalid_frontmatter(self) -> None:
        self.run_cli("init")
        unsafe = {
            "filename": "../outside.md",
            "content": "---\ntype: note\nstack: []\nstatus: active\n---\n",
            "indexDescription": "Unsafe.",
        }
        code, _, _ = self.run_cli("upsert", "--payload", "-", stdin=unsafe)
        self.assertEqual(code, 2)
        invalid = {
            "filename": "invalid.md",
            "content": "# Missing metadata\n",
            "indexDescription": "Invalid.",
        }
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=invalid)
        self.assertEqual(code, 2)
        self.assertIn("frontmatter", error)

        empty_value = {
            "filename": "empty-value.md",
            "content": "---\ntype:\nstack: []\nstatus: active\n---\n",
            "indexDescription": "Invalid.",
        }
        code, _, error = self.run_cli("upsert", "--payload", "-", stdin=empty_value)
        self.assertEqual(code, 2)
        self.assertIn("type", error)

    def test_rejects_vault_symlink_escape(self) -> None:
        with tempfile.TemporaryDirectory() as outside_name:
            outside = Path(outside_name)
            (self.workspace / "EchoesVault").symlink_to(outside, target_is_directory=True)
            code, _, error = self.run_cli("init")
            self.assertEqual(code, 2)
            self.assertIn("escapes the workspace", error)

    def test_end_requires_explicit_confirmation(self) -> None:
        self.run_cli("init")
        payload = {"dailySummary": "- Completed tests.", "pages": [], "indexUpdates": []}
        code, _, error = self.run_cli("end", "--payload", "-", stdin=payload)
        self.assertEqual(code, 2)
        self.assertIn("confirm-explicit-user-end", error)
        code, output, _ = self.run_cli(
            "end", "--confirm-explicit-user-end", "--payload", "-", stdin=payload
        )
        self.assertEqual(code, 0)
        self.assertTrue(json.loads(output)["memorySaved"])
        daily_files = list((self.workspace / "EchoesVault" / "daily").rglob("*.md"))
        self.assertEqual(len(daily_files), 1)
        self.assertIn("Completed tests", daily_files[0].read_text(encoding="utf-8"))

    def test_generated_index_is_sorted_and_ignores_page_body_changes(self) -> None:
        self.run_cli("init")
        for filename, summary in (
            ("zeta.md", "Zeta knowledge."),
            ("alpha.md", "Alpha knowledge."),
        ):
            payload = {
                "filename": filename,
                "content": (
                    "---\ntype: note\nstack: []\nstatus: active\n"
                    f"summary: {summary}\n---\n\n# Page\n\nBody one.\n"
                ),
            }
            code, _, error = self.run_cli("upsert", "--payload", "-", stdin=payload)
            self.assertEqual(code, 0, error)

        index = self.workspace / "EchoesVault" / "index.md"
        before = index.read_text(encoding="utf-8")
        self.assertLess(before.index("[[alpha]]"), before.index("[[zeta]]"))

        page = self.workspace / "EchoesVault" / "pages" / "zeta.md"
        updated = {
            "filename": "zeta.md",
            "content": page.read_text(encoding="utf-8").replace("Body one.", "Body two."),
            "expectedSha256": echoes_vault.sha256_text(page.read_text(encoding="utf-8")),
        }
        code, output, error = self.run_cli("upsert", "--payload", "-", stdin=updated)
        self.assertEqual(code, 0, error)
        self.assertFalse(json.loads(output)["indexChanged"])
        self.assertEqual(index.read_text(encoding="utf-8"), before)

    def test_legacy_index_description_migrates_to_summary(self) -> None:
        self.run_cli("init")
        page = self.workspace / "EchoesVault" / "pages" / "legacy.md"
        page.write_text(
            "---\ntype: decision\nstack: []\nstatus: active\n---\n\n# Legacy\n",
            encoding="utf-8",
        )
        index = self.workspace / "EchoesVault" / "index.md"
        index.write_text(
            echoes_vault.DEFAULT_INDEX + "\n- [[legacy]]: Migrated legacy description.\n",
            encoding="utf-8",
        )

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(status["indexRefresh"]["migratedSummaries"], ["legacy.md"])
        self.assertIn("summary: \"Migrated legacy description.\"", page.read_text())
        self.assertIn("[[legacy]]: Migrated legacy description.", index.read_text())

    def test_status_preserves_index_when_page_metadata_is_invalid(self) -> None:
        self.run_cli("init")
        index = self.workspace / "EchoesVault" / "index.md"
        before = index.read_text(encoding="utf-8")
        broken = self.workspace / "EchoesVault" / "pages" / "broken.md"
        broken.write_text(
            "---\ntype: note\nstack: []\nstatus: active\n---\n\n# Broken\n",
            encoding="utf-8",
        )

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(index.read_text(encoding="utf-8"), before)
        self.assertEqual(status["health"]["integrity"], "attention")
        self.assertEqual(status["health"]["invalidFrontmatter"], ["broken"])
        self.assertTrue(status["health"]["indexBuildErrors"])

    def test_index_rejects_unicode_equivalent_page_names(self) -> None:
        with self.assertRaisesRegex(echoes_vault.EchoesError, "collide across filesystems"):
            echoes_vault.validate_unique_page_names(
                [Path("café.md"), Path("cafe\u0301.md")]
            )

    def test_status_detects_git_conflict_markers(self) -> None:
        self.run_cli("init")
        page = self.workspace / "EchoesVault" / "pages" / "conflicted.md"
        page.write_text(
            "---\ntype: note\nstack: []\nstatus: active\n"
            "summary: Conflicted page.\n---\n\n<<<<<<< HEAD\nA\n=======\nB\n>>>>>>> branch\n",
            encoding="utf-8",
        )
        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        status = json.loads(output)
        self.assertEqual(status["health"]["conflictMarkers"], ["pages/conflicted.md"])
        self.assertEqual(status["health"]["integrity"], "attention")

    def test_each_log_write_uses_a_unique_file(self) -> None:
        self.run_cli("init")
        for entry in ("One", "Two"):
            code, _, error = self.run_cli("append", "--payload", "-", stdin={"entry": entry})
            self.assertEqual(code, 0, error)
        daily_files = list((self.workspace / "EchoesVault" / "daily").rglob("*.md"))
        self.assertEqual(len(daily_files), 2)
        self.assertEqual(len({item.name for item in daily_files}), 2)
        self.assertTrue(all(item.parent.name == echoes_vault.today() for item in daily_files))

    def test_parallel_writes_keep_every_page_indexed(self) -> None:
        self.run_cli("init")

        def create_page(number: int) -> subprocess.CompletedProcess[str]:
            payload = {
                "filename": f"parallel-{number}.md",
                "content": (
                    "---\ntype: note\nstack: [test]\nstatus: active\n"
                    f"summary: Parallel page {number}.\n---\n\n# Parallel {number}\n"
                ),
            }
            return subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--workspace",
                    str(self.workspace),
                    "upsert",
                    "--payload",
                    "-",
                ],
                input=json.dumps(payload),
                capture_output=True,
                text=True,
            )

        with ThreadPoolExecutor(max_workers=8) as pool:
            results = list(pool.map(create_page, range(24)))
        self.assertTrue(all(result.returncode == 0 for result in results))

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["totalPages"], 24)
        self.assertEqual(health["indexTopics"], 24)
        self.assertEqual(health["orphanPages"], [])
        self.assertEqual(health["integrity"], "healthy")

    def test_independent_git_branches_merge_without_generated_file_conflicts(self) -> None:
        def git(*args: str) -> subprocess.CompletedProcess[str]:
            return subprocess.run(
                ["git", "-C", str(self.workspace), *args],
                check=True,
                capture_output=True,
                text=True,
            )

        git("init", "-b", "main")
        git("config", "user.name", "EchoesVault Test")
        git("config", "user.email", "echoes@example.invalid")
        self.run_cli("init")
        git("add", "-A")
        git("commit", "-m", "Initialize vault")
        self.assertNotIn("EchoesVault/index.md", git("ls-files").stdout.splitlines())

        git("switch", "-c", "developer-a")
        page_a = {
            "filename": "alpha.md",
            "content": (
                "---\ntype: note\nstack: [git]\nstatus: active\n"
                "summary: Knowledge from developer A.\n---\n\n# Alpha\n"
            ),
        }
        self.assertEqual(self.run_cli("upsert", "--payload", "-", stdin=page_a)[0], 0)
        self.assertEqual(self.run_cli("append", "--payload", "-", stdin={"entry": "A"})[0], 0)
        git("add", "-A")
        git("commit", "-m", "Add developer A knowledge")

        git("switch", "main")
        git("switch", "-c", "developer-b")
        page_b = {
            "filename": "beta.md",
            "content": (
                "---\ntype: note\nstack: [git]\nstatus: active\n"
                "summary: Knowledge from developer B.\n---\n\n# Beta\n"
            ),
        }
        self.assertEqual(self.run_cli("upsert", "--payload", "-", stdin=page_b)[0], 0)
        self.assertEqual(self.run_cli("append", "--payload", "-", stdin={"entry": "B"})[0], 0)
        git("add", "-A")
        git("commit", "-m", "Add developer B knowledge")
        merge = git("merge", "--no-edit", "developer-a")
        self.assertNotIn("CONFLICT", merge.stdout + merge.stderr)

        code, output, error = self.run_cli("status")
        self.assertEqual(code, 0, error)
        health = json.loads(output)["health"]
        self.assertEqual(health["totalPages"], 2)
        self.assertEqual(health["totalDailyLogs"], 2)
        self.assertEqual(health["integrity"], "healthy")
        generated_index = (self.workspace / "EchoesVault" / "index.md").read_text()
        self.assertIn("[[alpha]]", generated_index)
        self.assertIn("[[beta]]", generated_index)


if __name__ == "__main__":
    unittest.main()
